### PR TITLE
Profile schema unique fix

### LINKED ISSUE #57: Remove events/set.js and replace all references to use functions/set.js (duplicate file)
I am using `functions/set.js` and have updated it on my branch, so please delete `events/set.js`. It has the same method inside but we don't want duplicate files

### PR DESCRIPTION
**Pull request by zade0123**
Closes #57

Changes DB schema for profiles and changes all queries to use the unique combination of (guildId, memberId) in place of just guildId to allow players to use the bot on multiple servers with distinct profiles

### CODE REVIEW

File: events/set.js
Comment (coreybriscoe) [inline events/set.js:1]: Great this closes #57

File: functions/serverData.js [hunk 1]
```diff
@@ -39,9 +39,15 @@ module.exports = {
 		};
 	},
 
-	getMemory: (client, guildIdString) => {
+	_getMemory: (client, guildIdString) => {
 		try {
-			return client.memory[guildIdString];
+			const guildMemory = client.memory[guildIdString];
+			if (guildMemory) {
+				// eslint-disable-next-line no-mixed-spaces-and-tabs
```
Comment (coreybriscoe) [inline functions/serverData.js]: remove the ESLint ignore comment and just fix the tabs/spaces problem

File: functions/serverData.js [hunk 2]
```diff
@@ -53,6 +59,12 @@ module.exports = {
 			return client.memory[guildIdString];
 		}
 	},
+	get getMemory() {
+		return this._getMemory;
+	},
+	set getMemory(value) {
```
Comment (coreybriscoe) [inline functions/serverData.js]: why did you use the get/set keywords? I really don't think this is what you meant to do

**Review by coreybriscoe — CHANGES_REQUESTED** [review]

**Review by coreybriscoe — APPROVED** [review]
LGTM
